# Generated by Django 5.2.13 on 2026-04-21 17:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('order', models.IntegerField(default=0)),
                ('horizontal_align', models.CharField(choices=[('start', 'Start (Left)'), ('center', 'Center'), ('end', 'End (Right)')], default='start', max_length=10)),
                ('vertical_align', models.CharField(choices=[('start', 'Top'), ('center', 'Middle'), ('end', 'Bottom'), ('stretch', 'Stretch')], default='start', max_length=10)),
                ('css_class', models.CharField(blank=True, max_length=255)),
                ('background_color', models.CharField(blank=True, max_length=50)),
                ('padding', models.CharField(blank=True, default='3', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template_name', models.CharField(max_length=255)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('config_schema', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('embed', 'Embed')], default='image', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='media_assets/')),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('config_template', models.JSONField()),
                ('content_template', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basecms.blocktype')),
            ],
        ),
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German')], max_length=10)),
                ('show_title', models.BooleanField(default=True)),
                ('layout', models.CharField(choices=[('grid', 'Grid'), ('vertical', 'Vertical')], default='vertical', max_length=50)),
                ('columns', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cms_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CMS Page',
                'verbose_name_plural': 'CMS Pages',
                'ordering': ['slug', 'language'],
                'unique_together': {('slug', 'language')},
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('span', models.IntegerField(default=1)),
                ('span_order', models.IntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='basecms.blocktype')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='basecms.cmspage')),
                ('parent_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_blocks', to='basecms.blockcolumn')),
            ],
            options={
                'ordering': ['position', 'span_order'],
            },
        ),
        migrations.CreateModel(
            name='ColumnBlockConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap', models.CharField(choices=[('0', 'No Gap'), ('1', 'Extra Small'), ('2', 'Small'), ('3', 'Medium'), ('4', 'Large'), ('5', 'Extra Large')], default='3', max_length=2)),
                ('row_horizontal_align', models.CharField(choices=[('start', 'Start'), ('center', 'Center'), ('end', 'End'), ('around', 'Space Around'), ('between', 'Space Between'), ('evenly', 'Space Evenly')], default='start', max_length=10)),
                ('stack_on_mobile', models.BooleanField(default=True)),
                ('row_css_class', models.CharField(blank=True, max_length=255)),
                ('row_background_color', models.CharField(blank=True, max_length=50)),
                ('row_padding', models.CharField(blank=True, default='3', max_length=50)),
                ('row_margin', models.CharField(blank=True, default='0', max_length=50)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='column_config', to='basecms.pageblock')),
            ],
        ),
        migrations.CreateModel(
            name='BlockItemQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(blank=True, max_length=255)),
                ('limit', models.IntegerField(default=10)),
                ('sort_field', models.CharField(default='created_at', max_length=255)),
                ('sort_order', models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], default='desc', max_length=10)),
                ('filters', models.JSONField(default=dict)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_query', to='basecms.pageblock')),
            ],
        ),
        migrations.AddField(
            model_name='blockcolumn',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='basecms.pageblock'),
        ),
        migrations.CreateModel(
            name='BlockAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('embed_code', models.TextField(blank=True)),
                ('caption', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('attachment_config', models.JSONField(default=dict)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_attachments', to='basecms.mediaasset')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='basecms.pageblock')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='basecms.cmspage')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Custom name for the link', max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', help_text='Language for this navbar item', max_length=10)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Determines the order of the links')),
                ('is_public', models.BooleanField(default=True)),
                ('cms_page', models.ForeignKey(blank=True, help_text='Select a CMS page (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navbar_items', to='basecms.cmspage')),
                ('parent', models.ForeignKey(blank=True, help_text='The parent of this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='basecms.navbaritem')),
            ],
            options={
                'verbose_name': 'NavbarItem',
                'verbose_name_plural': 'NavbarItems',
                'ordering': ['language', 'parent_id', 'sort_order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('language', 'parent', 'sort_order', 'title'), name='basecms_navbaritem_lang_parent_sort_title_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='pageblock',
            index=models.Index(fields=['page', 'position'], name='basecms_pag_page_id_c89b23_idx'),
        ),
        migrations.AddIndex(
            model_name='blockcolumn',
            index=models.Index(fields=['block', 'order'], name='basecms_blo_block_i_02c8a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pageversion',
            unique_together={('page', 'version_number')},
        ),
    ]
